"""add violation updated_at

Revision ID: 4c26861e0d8c
Revises: b6a2d4e3c701
Create Date: 2026-07-08 18:56:33.803639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c26861e0d8c'
down_revision: Union[str, Sequence[str], None] = 'b6a2d4e3c701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__alembic_tmp_audit_feedback_organization_id'), table_name='audit_feedback')
    op.drop_index(op.f('ix__alembic_tmp_audit_feedback_user_id'), table_name='audit_feedback')
    op.add_column('violations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('violations', 'updated_at')
    op.create_index(op.f('ix__alembic_tmp_audit_feedback_user_id'), 'audit_feedback', ['user_id'], unique=False)
    op.create_index(op.f('ix__alembic_tmp_audit_feedback_organization_id'), 'audit_feedback', ['organization_id'], unique=False)
    # ### end Alembic commands ###
