"""add submitted_by_id to review_tasks

Revision ID: b4998f14f159
Revises: bc5f67918c07
Create Date: 2026-07-08 21:22:17.070586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4998f14f159'
down_revision: Union[str, Sequence[str], None] = 'bc5f67918c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_tasks', sa.Column('submitted_by_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_tasks', 'submitted_by_id')
    # ### end Alembic commands ###
